name: HitboxBind
version: 1.0.2
main: cz.projectsurvive.limeth.hitboxbind.HitboxBind
author: Limeth
depend: [FramePicture]
commands:
    hitboxbind:
        description: 'Admin commands for the HitboxBind plugin'
        aliases: [hitbox, hbbind, hbb]